DROP TABLE IF EXISTS COMMENTAIRE;
DROP TABLE IF EXISTS FIL;
DROP TABLE IF EXISTS FOLLOW;
DROP TABLE IF EXISTS TACHE;
DROP TABLE IF EXISTS CAT;
DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS COMPTE;

CREATE TABLE COMPTE (
    ID_COM INT NOT NULL AUTO_INCREMENT,
    MAIL VARCHAR(100) NOT NULL,
    MDP VARCHAR(250) NOT NULL,
    TEL VARCHAR(20),
    NOM VARCHAR(50) NOT NULL,
    PRENOM VARCHAR(50) NOT NULL,
    ADMIN BOOLEAN NOT NULL,
    PRIMARY KEY (ID_COM)
);

CREATE TABLE NOTIFICATION (
    ID_NOTIF INT NOT NULL AUTO_INCREMENT,
    ID_COM INT NOT NULL,
    MESSAGE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_NOTIF),
    FOREIGN KEY (ID_COM) REFERENCES COMPTE(ID_COM) ON DELETE CASCADE
);

CREATE TABLE CAT(
    ID_CAT INT NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_CAT)
);

CREATE TABLE TACHE (
    ID_TCH INT NOT NULL AUTO_INCREMENT,
    CREATOR INT NOT NULL,
    NOM VARCHAR(255) NOT NULL, 
    DAY DATE NOT NULL,
    CAT INT,
    DESCRIPTION VARCHAR(255),
    ACTIF BOOLEAN NOT NULL,
    PRIMARY KEY (ID_TCH),
    FOREIGN KEY (CREATOR) REFERENCES COMPTE(ID_COM) ON DELETE CASCADE,
    FOREIGN KEY (CAT) REFERENCES CAT(ID_CAT) ON DELETE SET NULL
);

CREATE TABLE FOLLOW (
    ID_TCH INT NOT NULL ,
    ID_COM INT NOT NULL,
    FOREIGN KEY (ID_COM) REFERENCES COMPTE(ID_COM) ON DELETE CASCADE,
    FOREIGN KEY (ID_TCH) REFERENCES TACHE(ID_TCH) ON DELETE CASCADE
);

CREATE TABLE FIL (
    ID_FIL INT NOT NULL AUTO_INCREMENT,
    CREATOR INT NOT NULL,
    TACHE INT NOT NULL,
    NOM VARCHAR(255) NOT NULL,
    DAY DATE NOT NULL,
    PRIMARY KEY (ID_FIL),
    FOREIGN KEY (CREATOR) REFERENCES COMPTE(ID_COM) ON DELETE CASCADE,
    FOREIGN KEY (TACHE) REFERENCES TACHE(ID_TCH) ON DELETE CASCADE
);

CREATE TABLE COMMENTAIRE (
    ID_CMT INT NOT NULL AUTO_INCREMENT,
    CREATOR INT NOT NULL,
    FIL INT NOT NULL,
    COMM VARCHAR(255) NOT NULL,
    DAY DATE NOT NULL,
    PRIMARY KEY (ID_CMT),
    FOREIGN KEY (CREATOR) REFERENCES COMPTE(ID_COM) ON DELETE CASCADE,
    FOREIGN KEY (FIL) REFERENCES FIL(ID_FIL) ON DELETE CASCADE
);

insert into COMPTE values ( 1, 'admin@admin.com', 'c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec', null, 'admin', 'admin', True);
